version: '3.4'

services:
  sandboxapi:
    image: sandboxapi
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3001:3001
